language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

deploy:
  skip_cleanup: true
  provider: releases
  edge: true
  token:
    secure: "hHGf31NeZe79bthzQsVZwgzUle3UWGD6S9pvNm57W8VPuYETeLDBirXJvNliph2nLS8kjXfiymDYkgJHYewrb2Yxz+PzuTnatptb0FYn1KSA/C7kiXpmJc9zS8hJ2YGBR56g4W5V5eDalG6GMLpYPTtHRBTwc96MTNAQjQ6kB7y4wcNv8VzcXL6WkoGW8TXUhtRuRWUIZVFtTHuYFg9fE3ICbCCWrQFs3NUZAjVneh5bY3lLw2MQn/6vcGijDFWP6ptSmji1DEEyzO61C9l0LxAR18DAPBnnUODGBRLWQTyqjftjRx+lWe5KuYa5A0hQ+Nup8lmtGaqsk+ugU3soym9wtmZsvEINf+KTYq+XluwZ03crcgNvGSIEz8zfelxqM/117+GwzPMx9Tx8JjSIgAoNvqtnV16bekekWv2xjapLzam2zH5hkyumAbsBoPIjtZtFsZZcQ25zIVF8X+cleoZ5lOKttgHsKn+FQVE+LkW6Hu2stL+hSe1U6N8jyDnFe9op21SvP+RmC2UnSy90G2nx8XuuHrm6xHWVBBliThvfVHbP79D6z8W1BOSp46RkrmMA2f3OTrTAPksh5VkdltJ2ww2cE0Fevv2iSp0QPG9j+/x5J3v6V+Bxim3F3Dl0Zw4J/M8+4PcbJ7SLGnlgRfasOhVK9sYuF9ptYXNYMjQ="
  file: target/*.jar
  on:
    tags: true
