language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

deploy:
  skip_cleanup: true
  provider: releases
  edge: true
  token:
    secure: "bt4g1g3ra59piV+Jf+E36h19UuD+/RfzKF58yJVZLcL9QTy8nS1jJDQkdJRrS0iRCSfpx4+BBWmN/UuobhdUJsgFo2lcA2tSqXJXLt3AIob9+IuHkOILUknXf3ZI30niTcUA2egOaG71M16QIZ/GbEijU600FBwXHAga/RX14tpyxLGRSwlnPVofAYL5aOjVQbsmjG8rVyR8YrlzrjhijCBbt/fw3fKGosPILGaexT2WdUZOQe8gDoe3yY7Bzbemrj9tHEBszZA9kLYVGzFPxA1ssQBkgMR2JHP62BVP48gyxpojlhqGqWZUJS6xelMaoVcdn+0cLEFe7qHrknzgPKzHH3jryziHBppJ5nueME/keKMhxAZuEch4pD8h1Nkb7ja1wYZV917iLJMj3OQHr/O0WSli50LRzSibMLr/zGTSxLf4wte0tM6ZPboALAcLh3z1tWDM4TX33YZ4Ura9sE6JD8NdnVASrbh4ckibsi8dfHJM7SWkH8/DHG0N81lDqxpZaozwL44ykTBE1CoMWZd597PsJ7DO5cOgSy2yJsqi4tVnmHRTEgJxUMN19snjPqGdWipmj9/EkKSyYXs8I3dOy79vTld8fQhsViyhdkxI0UOst6V0SaLV+JfJKaYAyKX9RX5TBqVgj64mhGTO5aHJldolv+c/VgwfcRSdpIk="
  file: target/*.jar
  on:
    tags: true
